Upload
Maher9596/Checklist pull request #16
Opened 2020-11-08 19:06 UTC by Maher9596

I have tested the upload functionality by creating the following HTML page.

![image](https://user-images.githubusercontent.com/72282480/98481813-80c5be80-2216-11eb-9ca4-9dc2572bb7fb.png)

When an image is uploaded it gets saved in the localStorage of the browser and then the picture is shown in our HTML page from the localStorage.

![image](https://user-images.githubusercontent.com/72282480/98481888-06e20500-2217-11eb-9812-6970f9275f71.png)

2020-11-09 19:41 UTC, Ma7eer commented on upload.js
> +var form = document.getElementById("form")
Use `const` instead of `var`

2020-11-09 19:43 UTC, Ma7eer requested changes
Here are a couple of items I think should be changed in `upload.js`:

- Use `const` and `let` instead of `var`.
- Add spacing between each section (will leave a comment about where I am referring)
- We should decide if we are using semi-colons or not. (You are using a mix of them in the file)

2020-11-09 19:44 UTC, Ma7eer commented on upload.js
> +form.addEventListener('submit', function(event){
Add spacing here

2020-11-09 19:45 UTC, Ma7eer commented on upload.js
> +function showImages() {
Lets use arrow functions

2020-11-10 16:12 UTC, Maher9596 commented
All changes requested have been made as shown in the **upload.js** file.

2020-11-10 18:41 UTC, Ma7eer commented on upload.js
> +let form = document.getElementById("form")
use const here

2020-11-10 18:41 UTC, Ma7eer commented on upload.js
> +let parentDiv = document.getElementById("result")
Add const here

2020-11-13 19:17 UTC, Ma7eer commented on upload.js
> +let form = document.getElementById("form")
```suggestion
const form = document.getElementById("form")
```

2020-11-13 19:18 UTC, Ma7eer commented on upload.js
> +let parentDiv = document.getElementById("result")
```suggestion
const parentDiv = document.getElementById("result")
```

2020-11-13 19:19 UTC, merged