creating PR to start working on UI of login page
Maher9596/Checklist pull request #41
Opened 2020-11-27 13:06 UTC by Maher9596

# start working on login page

2020-11-28 16:54 UTC, Maher9596 commented
# Login page UI
- I styled the UI for the login page using my own styling + Font awesome library
- I added a **Forgot password** link (We can discuss and decide whether we want to keep it there or not)
# Issues
- I faced this issue while trying to connect my CSS file to my ejs file I got the following error

![image](https://user-images.githubusercontent.com/72282480/100521139-41f2ab00-31bb-11eb-8fa5-e332266e0fea.png)

It seemed to me that **Express** did not know where to find my CSS file, So I did my research and found out that we need to specify where can express find all of our static files, And from **Express documentation** I found that we can do that by adding this line of code.
![image](https://user-images.githubusercontent.com/72282480/100521245-c04f4d00-31bb-11eb-893e-877417b31942.png)

2020-12-04 07:54 UTC, Ma7eer commented on public/login.css
> +  background: radial-gradient(#9b30ff, #9225a7, #7f2092);
All our colors should be in variables. read about [css variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties).

2020-12-04 07:57 UTC, Ma7eer commented on public/login.css
> +  width: 430px;
No [magic numbers](https://en.wikipedia.org/wiki/Magic_number_(programming)).

2020-12-04 07:58 UTC, Ma7eer commented on views/pages/login.ejs
> +            const pswrd = document.getElementById('pswrd')
```suggestion
            const password = document.getElementById('pswrd')
```

2020-12-04 07:59 UTC, Ma7eer commented on views/pages/login.ejs
> +
```suggestion

```

2020-12-04 08:08 UTC, Ma7eer requested changes
I added some comments to help make the code more readable. 

In addition, see below for some comments on the UI:

- I don't like the color of the font. Lets stick to our main colors: purple,grey, white
- The horizontal line below the title is unnecessary.
- The gradient is currently going to the center lets add some [angles](https://www.quirksmode.org/css/images/angles.html) to it.  
- The form is too low. it should be on the center vertically and horizontally.
- Remove the forget password link as we won't be adding that functionality.

2023-04-20 06:05 UTC, closed without merging